### PR TITLE
Add KSP processor implementation

### PR DESCRIPTION
**Pull request by alexvanyo**
This PR adds an alternative code generation implementation via [`ksp`](https://github.com/google/ksp).

@cdflynn This PR is almost the same as #72, with added support for sealed interfaces. I'm opening up a new PR here since the merge history got pretty messy.

The only difference that you didn't approve is the last commit, https://github.com/livefront/sealed-enum/commit/ab20c3db940c5ed8930d985249c3aaf4bac59809

One commit also became redundant, since it was merged with the `sealed-interface` PR.

### CODE REVIEW

**Comment by cdflynn** [comment]
Thanks @alexvanyo!

I was running tests locally again and getting a strange error in a handful of them.  CI had no problem [running the tests](https://github.com/livefront/sealed-enum/pull/76/checks?check_run_id=3167686298), so I assume this is a me problem.

```
./gradlew test 

> Task :processing-tests:ksp-tests:test FAILED
[...]
209 tests completed, 44 failed, 3 skipped
```

They're all the same thing, 

Screen Shot 2021-07-27 at 11 52 14 AM

The `compile` throws with:
> e: [ksp] org.jetbrains.kotlin.resolve.lazy.NoDescriptorForDeclarationException: Descriptor wasn't found for declaration PROPERTY

I've been switching between projects a lot so it's possible I got into a bad state.  I did a few things just to rule out common configuration/local problems, 
- nuke gradle caches from orbit
- clean/invalidate restart

Just curious if you've seen this one before!

**Comment by alexvanyo** [comment]
@cdflynn I was able to reproduce locally on macOS, I developed this PR on Linux so didn't run into this myself. Just updated CI to also run on macOS and Windows, and I'm seeing the same thing there.

Since it's only the `compiling` tests that are failing, my guess is that it has something to do with how `kotlin-compile-testing` works.

I wonder if case-sensitivity of the filesystem is messing something up perhaps?

**Comment by cdflynn** [comment]
> Since it's only the `compiling` tests that are failing, my guess is that it has something to do with how `kotlin-compile-testing` works.
> 
> I wonder if case-sensitivity of the filesystem is messing something up perhaps?

Yeah, interesting!  A glance through the `issues` (open and close) on `kotlin-compile-testing` doesn't show anything familiar.  If I can get some time after hours today I'll run some comparisons with different versions of the `kotlin-compile-testing` and `kotlin` itself.  It is funny that both mac and windows have the same fails.  If it's possible to reduce this down to an atomic failure example, that could make for a new `issue` to post.

**Comment by alexvanyo** [comment]
Closed, found https://github.com/google/ksp/issues/427 as a related issue.

**Comment by alexvanyo** [comment]
Whoops, closed the wrong branch :sweat_smile:

**Comment by alexvanyo** [comment]
@cdflynn I found https://github.com/google/ksp/issues/427, which looks like a pretty similar issue to what we're running into here. I'm going to add the information to that bug about what we were seeing here, but based on that issue it looks like it is some very strange issue that happens when all of the following are true:
- `kotlin-compile-testing` is being used to compile the code and run `KSP`
- `KSP` is being run and looking for annotations
- `KotlinPoet` is being used to generate code based on those
- Running on macOS or Windows

Since this is only impacting testing (and only the `kotlin-compile-testing` tests, and only on some operating systems), I feel like we should be okay to merge, if you're comfortable with that.

**Comment by alexvanyo** [comment]
@cdflynn Progress?

I just updated to `1.0.0-beta09`, and now `macOS` is passing, but all of the Windows builds are still failing.

**Comment by cdflynn** [comment]
> I just updated to `1.0.0-beta09`, and now `macOS` is passing

It now officially `"works on my machine"` 😄

**Comment by alexvanyo** [comment]
Ah ha! The good news is the Windows errors are now different, and are similar to this:

https://github.com/livefront/sealed-enum/runs/3500245957?check_suite_focus=true#step:7:2743

```
    e: [ksp] java.lang.IllegalArgumentException: this and base files have different roots: D:\a\sealed-enum\sealed-enum\processing-tests\ksp-tests\..\common\src\jvmTest\kotlin\com\livefront\sealedenum\compilation\basic\OneObjectSealedInterface.kt and C:\Users\RUNNER~1\AppData\Local\Temp\Kotlin-Compilation3636371620958659314\ksp.
    	at kotlin.io.FilesKt__UtilsKt.toRelativeString(Utils.kt:117)
    	at kotlin.io.FilesKt__UtilsKt.relativeTo(Utils.kt:128)
    	at com.google.devtools.ksp.IncrementalContext.toRelativeFile(Incremental.kt:223)
    	at com.google.devtools.ksp.IncrementalContext.getRelativeFile(Incremental.kt:225)
    	at com.google.devtools.ksp.IncrementalContext.recordGetSealedSubclasses(Incremental.kt:760)
    	at com.google.devtools.ksp.symbol.impl.kotlin.KSClassDeclarationImpl.getSealedSubclasses(KSClassDeclarationImpl.kt:53)
    	at com.livefront.sealedenum.internal.ksp.SealedEnumProcessor.createSealedClassNode(SealedEnumProcessor.kt:211)
    	at com.livefront.sealedenum.internal.ksp.SealedEnumProcessor.createSealedEnumFileSpec(SealedEnumProcessor.kt:165)
    	at com.livefront.sealedenum.internal.ksp.SealedEnumProcessor.process(SealedEnumProcessor.kt:61)
```

So it looks like [the temporary directory](https://github.com/tschuchortdev/kotlin-compile-testing/blob/17eed5d0517ea1e09a08bb1b4f7255df6011c170/core/src/main/kotlin/com/tschuchort/compiletesting/AbstractKotlinCompilation.kt#L32) that `kotlin-compile-testing` uses ends up being underneath the `C` drive, whereas the GitHub Actions worker checkout is on the `D` drive.

The most straightforward solution seems to be to update the `TMP` environment variable on Windows to be underneath the `D` drive, so that the temporary directories that Java creates aren't causing us to try to cross drives while compiling.

**Comment by alexvanyo** [comment]
@cdflynn 🥳 , we've got ourselves a passing build! https://github.com/livefront/sealed-enum/actions/runs/1196034931

Just cleaned up the `TMP` environment variable setting slightly, and now this should be ready!

**Comment by cdflynn** [comment]
Nice detective work @alexvanyo 

```
run: echo "TMP=${{ runner.temp }}" >> $env:GITHUB_ENV
```

and of course it's `yaml` where we can configure that, with syntax you have look up 🙃

**Review by cdflynn — APPROVED** [review]
this PR is approved AF

**Pull request merged**
